### ISSUE TITLE
GetBotChannelAssociations

### ISSUE THREAD

**Issue by amar-preet** [awsdocs/amazon-lexv2-developer-guide#1]
Is there a way to get bot channel associations in the V2 version? There is an API in [the V1 ](https://docs.aws.amazon.com/lex/latest/dg/API_GetBotChannelAssociations.html)version but not in V2.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
