### ISSUE TITLE
How is it that the documented intent states in Lex are different from the actual available values?What is the difference between each of these states?

### ISSUE THREAD

**Issue by karimfayed** [awsdocs/amazon-lexv2-developer-guide#4]
I am currently working on integrating aws Lex with lambda function written in TypeScript and I am facing a situation in which I need help .

**Upon reading the aws documentation for LexV2 the following values are available for an intent state:**

 - Failed
 - Fulfilled
 - FulfillmentInProgress
 - InProgress
 - ReadyForFulfillment
 - Waiting

**However when I used the 'Waiting' value, The following error message showed up :**  

> Invalid Lambda Response: Received invalid response from Lambda: Can not deserialize value of type Intent$IntentState from String "Waiting": value not one of declared Enum instance names: [ReadyForFulfillment, InProgress, Failed, Fulfilled]

**Upon this I need help to:**

 1. Understand how is it possible to have values that are not recognized.
 2. Understand the difference between each of these values (*Note: not all of the accepted values are explained in the documentation*)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
